update poetry version 1.1.14 -> 1.2.0

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -8,12 +8,10 @@ ENV PYTHONUNBUFFERED=1 \
     POETRY_HOME="/opt/poetry" \
     POETRY_VIRTUALENVS_IN_PROJECT=true \
     POETRY_NO_INTERACTION=1 \
-    PYSETUP_PATH="/opt/pysetup" \
-    VENV_PATH="/opt/pysetup/.venv"
+    PYSETUP_PATH="/opt/pysetup" 
 
-ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
 
-# builder-base is used to build dependencies
+# Builder-base is used to build dependencies
 FROM python-base AS builder-base
 RUN buildDeps="build-essential" \
     && apt-get update \
@@ -24,35 +22,37 @@ RUN buildDeps="build-essential" \
     && apt-get install -y --no-install-recommends $buildDeps \
     && rm -rf /var/lib/apt/lists/*
 
-# Install Poetry - respects $POETRY_VERSION & $POETRY_HOME
-ENV POETRY_VERSION=1.1.14
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
-RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python && \
-    chmod a+x /opt/poetry/bin/poetry
-
 # We copy our Python requirements here to cache them
-# and install only runtime deps using poetry
 WORKDIR $PYSETUP_PATH
 COPY ./poetry.lock ./pyproject.toml ./
-RUN poetry install --no-dev --no-root  # respects
 
 # 'development' stage installs all dev deps and can be used to develop code.
 # For example using docker-compose to mount local volume under /app
 FROM python-base as development
 ENV FASTAPI_ENV=development
 
-# Copying poetry and venv into image
-COPY --from=builder-base $POETRY_HOME $POETRY_HOME
+# Copying poetry and deps into image
 COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH
+
+WORKDIR $PYSETUP_PATH
+ENV POETRY_VERSION=1.2.0
+
+# Install poetry
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN pip install "poetry==$POETRY_VERSION"
+
+# (https://github.com/python-poetry/poetry/issues/3219)
+# If frequent intermittent connection failures, uncomment the following line 
+# RUN poetry config installer.parallel false
+
+# Install our project dependencies
+RUN poetry install --no-root --only main  
 
 # Copying in our entrypoint
 COPY ./docker/docker-entrypoint.sh /docker-entrypoint.sh
 RUN chmod +x /docker-entrypoint.sh
 
-# venv already has runtime deps installed we get a quicker install
-WORKDIR $PYSETUP_PATH
-RUN poetry install --no-root
-
+# Copying project
 WORKDIR /app
 COPY . .
 
